version: 2

sources:
  - name: teddy_retailers_sales
    description: These are the tables that our extraction software manages most likely through batch jobs. 
    tables:
      - name: source_customers
        columns:
        - name: customer_id
          tests:
          - unique
          - not_null
      - name: source_orders
        columns:
        - name: order_id
          tests:
          - unique
          - not_null
        - name: customer_id
          tests:
          - unique
          - not_null
      - name: source_order_products
        columns:
        - name: order_id
          tests:
          - unique
          - not_null
        - name: product_id
          tests:
          - unique
          - not_null

